import ReduxProviders from "@/redux/ReduxProvider";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Mulish } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Kurated App",
  description: "Generated by create next app",
};

const mulish = Mulish({ subsets: ["latin"] });
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,200..1000;1,200..1000&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={`${mulish.className} antialiased`}>
        <AntdRegistry>
          <ReduxProviders>{children}</ReduxProviders>
        </AntdRegistry>
      </body>
    </html>
  );
}
